# Generated by Django 3.2.6 on 2021-10-22 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('nutrition_grade', models.CharField(max_length=255)),
                ('stores', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('salt', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('proteins', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='foods.product')),
            ],
        ),
    ]
