# Generated by Django 3.2.6 on 2022-01-19 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_product_notation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
