# Generated by Django 3.2.6 on 2022-01-27 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_product_notation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notation',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
