before_install:
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - export CHROME_BIN=chromium-browser

language: python

python:
  - "3.9"

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE='nutella_project.travis'

before_script:
  - pip install -r requirements.txt

script:
  - ./manage.py test