before_install:
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/


language: python

python:
  - "3.9"

addons:
  chrome: stable
      
services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE='nutella_project.settings'

script:
  - ./manage.py test