before_install:
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - export CHROME_BIN=chromium-browser

language: python

python:
  - "3.9"

addons:
  chrome: stable
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

services:
  - postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=nutella_project.settings
    - PGPORT=5432

cache: pip

before_script:
  - pip install -r requirements.txt

script:
  - python manage.py test