language: python

python:
  - "3.9"

before-install:
  - "export DISPLAY=99:0"
  - sleep 3

addons:
  chrome: stable
      
services:
  - postgresql
  - xvfb

env:
  - DJANGO_SETTINGS_MODULE='nutella_project.settings'

before_script:
  - chmod +x ./manage.py
  - wget -N https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - google-chrome-stable --no-sandbox --disable-dev-shm-usage --headless --start-maximized --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - ./manage.py test