language: python

python:
  - "3.9"

before-install:
  - "export DISPLAY=99:0"
  - sleep 3

addons:
  chrome: stable
      
services:
  - postgresql
  - xvfb
  
env:
  - DJANGO_SETTINGS_MODULE='nutella_project.settings'

before_script:
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/build/P_10_PurBeurre/
  - export CHROME_BIN=chromium-browser

script:
  - ./manage.py test