language: python

python:
  - "3.9"

addons:
  chrome: stable
  
before_install:
  - "export DISPLAY=99:0"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &   

services:
  - postgresql
  - xvfb

env:
  - DJANGO_SETTINGS_MODULE='nutella_project.settings'

before_script:
  - echo $PATH
  - chmod +x ./manage.py
  - wget -N https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d /home/travis/virtualenv/python3.9.7/bin/
  - export CHROME_BIN=chromium-browser
  - export PATH=/home/travis/virtualenv/python3.9.7/bin/c:$PATH

script:
  - ./manage.py test