before_install:
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip
  - mkdir chromedriver_linux64
  - unzip chromedriver_linux64.zip -d ~/
  - export PATH=$PATH:$PWD/chromedriver


language: python

python:
  - "3.9"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      
services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE='nutella_project.settings'

before_script:
  - pip install -r requirements.txt

script:
  - ./manage.py test