sudo: required

language: python

dist: xenial

python:
  - "3.9"

addons:
  chrome: stable
  
before_install:
- google-chrome-stable --no-sandbox --disable-dev-shm-usage --headless --start-maximized --disable-gpu --remote-debugging-port=9222 http://localhost &

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE='nutella_project.settings'

before_script:
  - echo $PATH
  - chmod +x ./manage.py
  - wget -N https://chromedriver.storage.googleapis.com/96.0.4664.45/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d usr/local/bin/

script:
  - ./manage.py test