language: python

python:
  - "3.9"

addons:
  chrome: stable
  
before_install:
- google-chrome-stable --no-sandbox --disable-dev-shm-usage --headless --start-maximized --disable-gpu --remote-debugging-port=9222 http://localhost &

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE='nutella_project.settings'

before_script:
  - echo $PATH
  - chmod +x ./manage.py
  - wget https://chromedriver.storage.googleapis.com/'cat LATEST_RELEASE'/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin/

script:
  - ./manage.py test