language: python

python:
  - "3.9"

addons:
  chrome: stable
      
services:
  - postgresql
  - xvfb

env:
  - DJANGO_SETTINGS_MODULE='nutella_project.settings'

before_script:
  - echo $PATH
  - chmod +x ./manage.py
  - wget -N https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d /home/travis/virtualenv/python3.9.7/bin/
  - export PATH=/home/travis/virtualenv/python3.9.7/bin/chromedriver:$PATH

script:
  - ./manage.py test