before_install:
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - sudo mv chromedriver /usr/local/bin 
  - sudo chmod +x /usr/local/bin/chromedriver


language: python

python:
  - "3.9"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      
services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE='nutella_project.settings'

script:
  - ./manage.py test